# Generated by Django 5.0.6 on 2024-07-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interface", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentvector",
            name="filename",
            field=models.TextField(default="a.txt"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentvector",
            name="page_number",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
